name: Run Testes
on:
    pull_request:
        branches: [master]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
          
            - name: Instalar dependencias 
              run: npm install

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with: 
                record: true
              env:
                CYPRESS_RECORD_KEY: 8ed60782-318c-4bd5-af76-d261db0acee7
            